name: "Upload SARIF"

on:
  push:
  schedule:
    - cron: '45 15 * * 4'  # Runs every Thursday at 15:45 UTC

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif  # Change this path if needed

